import pygame

pygame.init()
pygame.font.init()

def game_rules(screen):
    title=pygame.font.Font(None, 50)
    text=pygame.font.Font (None, 42)
    
    title_r = title.render("GAME RULES/COMPONENTS", True, (0,0,0))
    rule_1 = text.render ("The board consists of 3 rows and 10 columns that make a total of 30 squares", True, (0,0,0))
    rule_2 = text.render ("Each player has five pieces (brown or white) to play", True, (0,0,0))
    rule_3 = text.render ("There are 6 houses that have specific characteristics (16, 26,27,28,29,30)", True, (0,0,0))
    rule_4 = text.render ("The pieces have to be alternated, i.e. one white followed by one black.", True, (0,0,0))
    rule_5 = text.render ("The pieces must be moved in a line, the first line from left to right, the second from right to left, and the third again from left to right. In the third row, when it reaches the end, we remove the piece from the board.", True, (0,0,0))
    rule_6 = text.render ("A group of three or better dancers blocks the passage of opposing pieces", True, (0,0,0))
    rule_7 = text.render ("When a piece is forced to move backward, it may not attack an opposing piece.", True, (0,0,0))
    rule_8 = text.render ("The House of Second Life is considered a safe house (that is, a piece on that House may not be attacked", True, (0,0,0))
    rule_9 = text.render ("The House of Second Life is considered a safe house and grants the player an extra turn.", True, (0,0,0))
    rule_10 = text.render ("The House of Beauty grants the player an extra turn.", True, (0,0,0))
    rule_11 = text.render ("While a piece is on the House of Humiliation, no other piece is allowed to enter it.", True, (0,0,0))
    rule_12 = text.render ("A piece that falls on the House of Humiliation is sent back to the very first (farthest) house.", True, (0,0,0))
    rule_13 = text.render ("A piece that falls on the House of Humiliation is removed from the game and must be re-entered at the very first (farthest) house.", True, (0,0,0))
    rule_14 = text.render ("Pieces on the last three Houses are allowed to move forward in addition to bearing off.", True, (0,0,0))
    rule_15 = text.render ("The last three Houses and the House of Beauty are considered safe houses.", True, (0,0,0))
    rule_16 = text.render ("If a throw allows the player to bear a piece off, he must do so.", True, (0,0,0))
    rule_17 = text.render ("A player may bear off his pieces only once they are all on the last row of the board.", True, (0,0,0))
    
    screen.fill((255, 255, 255))
    screen.blit(title_r, (200, 100)) 
    screen.blit(rule_1, ())
    screen.blit(rule_2, ())
    screen.blit(rule_3, ())
    screen.blit(rule_4, ())
    screen.blit(rule_5, ())
    screen.blit(rule_6, ())
    screen.blit(rule_7, ())
    screen.blit(rule_8, ())
    screen.blit(rule_9, ())
    screen.blit(rule_10, ())
    screen.blit(rule_11, ())
    screen.blit(rule_12, ())
    screen.blit(rule_13, ())
    screen.blit(rule_14, ())
    screen.blit(rule_15, ())
    screen.blit(rule_16, ())
    screen.blit(rule_17, ())